<package format="3">
  <name>hpp_rviz</name>
  <version>8.0.0</version>
  <description>Rviz plugins for hpp visualization</description>

  <maintainer email="guilhem.saurel@laas.fr">Guilhem Saurel</maintainer>

  <author>Joseph Mirabel</author>
  <author>Florent Lamiraux</author>
  <license>BSD-2-Clause</license>

  <url type="website">https://github.com/humanoid-path-planner/hpp_rviz</url>
  <url type="repository">https://github.com/humanoid-path-planner/hpp_rviz</url>
  <url type="bugtracker">https://github.com/humanoid-path-planner/hpp_rviz/issues</url>

  <buildtool_depend>cmake</buildtool_depend>
  <build_depend>doxygen</build_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <depend>rosidl_default_runtime</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>rviz_common</depend>
  <depend>rviz_default_plugins</depend>
  <depend>rviz_rendering</depend>
  <depend>pluginlib</depend>
  <depend>ament_cmake_ros</depend>
  <depend>python3</depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
